### ISSUE TITLE
Week 3: JavaScript notes

### ISSUE THREAD

**Issue by AbleLincoln** [talent-path-la/class-notes-track-6#3]
- [ ] Values, Types, and Operators
- [ ] Program Structure
- [ ] Functions
  - [ ] callbacks
  - [x] arrow functions
  - [ ] closures
- [ ] Class
  - [ ] constructors
  - [ ] prototypes
- [ ] Strings
  - [ ] template literals
  - [ ] advanced objects: Map, Set
- [ ] Arrays
- [ ] Objects
  - [ ] OOP
  - [ ] protoypes and inheritance
- [ ] Higher-order Functions
- [ ] The Secret Life of Objects
- [ ] Bugs and Errors
  - [ ] try, catch
- [ ] ES6 goodies
  - [ ] spread, rest
  - [ ] arrow functions
  - [ ] destructuring
  - [x] let, const, var
- [ ] Modules
- [ ] Asynchronous Programming
  - [ ] callbacks
  - [ ] promises
  - [ ] async/await
- [ ] Jest

**Comment by ScotteRoberts** [comment]
@AbleLincoln We need to think of some challenges that Track 3 can do while we are going over the basics.

**Comment by AbleLincoln** [comment]
Agreed. [Eloquent JavaScript](https://eloquentjavascript.net) has some good exercises. I am currently going through and will pull anything that looks interesting

**Comment by ScotteRoberts** [comment]
Take a look at my pull request for notes. I pulled from Eloquent JavaScript and MDN docs as main sources.
