### ISSUE TITLE
Vet Git Lesson

### ISSUE THREAD

**Issue by AbleLincoln** [talent-path-la/class-notes-track-6#4]
Can you go through the [git lesson](https://github.com/talent-path-la/class-notes-track-6/tree/master/week1#git) and see if it all checks out?

**Comment by AbleLincoln** [comment]
Would be nice to include screen grabs of GitKraken in use

**Comment by ScotteRoberts** [comment]
I remember that diagram being very confusing to everyone the first time they say it. Do you have a step-by-step to explain it?

Do you want me to go through each of the steps in the instruction set and get screenshots?

**Comment by ScotteRoberts** [comment]
We have to give them the referral link when we get them to use GitKraken.

**Comment by ScotteRoberts** [comment]
![git-flow](https://user-images.githubusercontent.com/17076638/59949717-d5ea1000-9428-11e9-89ed-726554cc72bd.png)
![git-flow-simple](https://user-images.githubusercontent.com/17076638/59949721-d7b3d380-9428-11e9-982f-0213ea3cb5c7.png)

**Comment by ScotteRoberts** [comment]
All of the images in order for the instruction set.

<img width="1439" alt="1_gitkraken-startup-page" src="https://user-images.githubusercontent.com/17076638/59958101-33e11c80-9456-11e9-9450-116ce81622b5.png">
<img width="1440" alt="2_cloning-a-repo" src="https://user-images.githubusercontent.com/17076638/59958102-33e11c80-9456-11e9-9dc2-928a6f2c429d.png">
<img width="1440" alt="3_successful-clone" src="https://user-images.githubusercontent.com/17076638/59958103-33e11c80-9456-11e9-97e7-d0b8495f31de.png">
<img width="1440" alt="4_branch-visualizer" src="https://user-images.githubusercontent.com/17076638/59958104-33e11c80-9456-11e9-9cad-d0cc55d27d12.png">
<img width="1440" alt="5_create-new-branch" src="https://user-images.githubusercontent.com/17076638/59958106-33e11c80-9456-11e9-8edb-29c7b4b90e51.png">
<img width="1440" alt="6_edit-content" src="https://user-images.githubusercontent.com/17076638/59958107-3479b300-9456-11e9-950d-dba8d35f3cd1.png">
<img width="1440" alt="7_commit" src="https://user-images.githubusercontent.com/17076638/59958108-3479b300-9456-11e9-86ff-01557d34a77e.png">
<img width="1440" alt="8_push" src="https://user-images.githubusercontent.com/17076638/59958109-3479b300-9456-11e9-850f-8ffbead0a52b.png">
<img width="1440" alt="9_set-upstream-branch" src="https://user-images.githubusercontent.com/17076638/59958110-3479b300-9456-11e9-9b9c-96094a091270.png">
<img width="1440" alt="10_github-make-pull-request" src="https://user-images.githubusercontent.com/17076638/59958111-3479b300-9456-11e9-85a2-1631a5a0ca5a.png">
<img width="1439" alt="11_github-make-pull-request-pt2" src="https://user-images.githubusercontent.com/17076638/59958112-35124980-9456-11e9-931f-9e51bb2b8c0f.png">
<img width="1440" alt="12_gitkraken-make-pull-request" src="https://user-images.githubusercontent.com/17076638/59958113-35124980-9456-11e9-907f-3ade243e56ba.png">
<img width="1440" alt="13_gitkraken-make-pull-request-pt2" src="https://user-images.githubusercontent.com/17076638/59958115-35124980-9456-11e9-8202-b0cfaa4d6a4f.png">
<img width="1440" alt="14_successful-pull-request" src="https://user-images.githubusercontent.com/17076638/59958116-35124980-9456-11e9-975d-361f4715ebbc.png">
